### ISSUE TITLE
Help | using latest v8 version - preview on drag elements in touch screens.

### ISSUE THREAD

**Issue by rohitkunala** [LouisBrunner/dnd-multi-backend#119]
For Desktop , I proceeded as per latest v8 docs suggest and preview is working fine for desktop.
For mobile( touch ) - Can you please update the docs on what changes to be done to get the preview on dragging elements ?

The below is my code - which works good (preview) for desktop and not for touch screens.

```
import { DndProvider } from "react-dnd-multi-backend";
import { HTML5toTouch } from 'rdndmb-html5-to-touch'

function Home() {
  return (
      <DndProvider options={HTML5toTouch}>
        <ReactComponent />
      </DndProvider>
  );
}
```

**Comment by LouisBrunner** [comment]
@rohitkunala 

Hi, please refer to the "Preview" section of `react-dnd-multi-backend` which explain 3 different ways (hook, context, function) to generate your preview: https://github.com/LouisBrunner/dnd-multi-backend/tree/main/packages/react-dnd-multi-backend#preview

Here is some example code https://github.com/LouisBrunner/dnd-multi-backend/blob/main/packages/react-dnd-multi-backend/examples/App.tsx#L68
