### ISSUE TITLE
Force use of Preview for any backend

### ISSUE THREAD

**Issue by flyon** [LouisBrunner/dnd-multi-backend#138]
Is there any way to use the Preview component even in environments where the native HTML5 API is supported? 
Because this package allows me to still render changes on the preview whilst it's being dragged, and the native doesn't seem to do that.

**Comment by LouisBrunner** [comment]
Hey @flyon,

In this case, you might want to use `react-dnd-touch-backend` directly with `react-dnd-preview` without using `react-dnd-multi-backend` at all. With `enableMouseEvents`, the backend should work on all devices and `react-dnd-preview` should be a drop-in replacement for the one from `react-dnd-multi-backend`.

**Comment by flyon** [comment]
Ah great. I'll try that. Thank you!
