### ISSUE TITLE
Can not import MultiBackend, { Preview } from 'react-dnd-multi-backend';

### ISSUE THREAD

**Issue by AubreyHewes** [LouisBrunner/dnd-multi-backend#16]
Following the docs/examples.. 
```
import MultiBackend, { Preview } from 'react-dnd-multi-backend';
```

fails with "Cannot have two MultiBackends at the same time."

`package.json`
```
    "react": "^16.1.1",
    "react-dnd": "^2.5.4",
    "react-dnd-multi-backend": "^3.0.4",
```

Importing separately removes the error...

```
import MultiBackend from 'react-dnd-multi-backend';
import Preview from 'react-dnd-multi-backend/lib/Preview';
```

**Comment by LouisBrunner** [comment]
Hi @AubreyHewes,

If you look in the examples, you can see that [App.js](https://github.com/LouisBrunner/react-dnd-multi-backend/blob/master/src/examples/App.js) uses the same import as you stated, and it works perfectly. Thus, I think your problem may come from somewhere else. Could you paste a full example that displays this issue? (if possible in a repository ready to be built?)

Thanks!

**Comment by AubreyHewes** [comment]
@LouisBrunner Sorry for the delay. This now works as expected.. :sheep:
