### ISSUE TITLE
this.props.generator is not a function

### ISSUE THREAD

**Issue by AubreyHewes** [LouisBrunner/dnd-multi-backend#17]
I have a component (react class) and would like it's DnD to be html5 and touch,  I tried to follow the [example](https://github.com/LouisBrunner/react-dnd-multi-backend/tree/0ebdec7b145e786b32d1fc0a3b3ec6af30d08a68/src/examples) I just can not get the touch preview to work (just fatals). I use the following in the main component render (to allow a touch preview?):

```
  <Preview generator={this.generatePreview} />
```

the class method `generatePreview` is currently  (a la the example) and as such is agnostic

```
  generatePreview = (type, item, style) => (
    <div style={{ ...style, backgroundColor: item.color, width: '50px', height: '50px' }}>
      Generated
    </div>
  );
```

I get the following error: 

```this.props.generator is not a function```

Stacktrace:
```
beginDrag {thing: Map}
cmp.js:52 {generator: ƒ, currentOffset: {…}, isDragging: true, itemType: "Thing", item: {…}, …}currentOffset: {x: 242.609375, y: 546}generator: ƒ generatePreview(type, item, style)isDragging: trueitem: {thing: Map}itemType: "Thing"ref: (...)get ref: ƒ ()__proto__: Object
Preview.js:53 Uncaught TypeError: this.props.generator is not a function
```
In the stacktrace the prop `generator` is clearly a function??

`package.json`
```
    "react": "^16.1.1",
    "react-dnd": "^2.5.4",
    "react-dnd-multi-backend": "^3.0.4",
```

I just can't seem to get this working, Thanks for any help!

**Comment by LouisBrunner** [comment]
Hi @AubreyHewes,

I tried your snippet to be sure and it works. So your issue must come from the rest of your code, would it be possible for you to provide a full example, including build system, package.json, etc?

Thanks!

**Comment by AubreyHewes** [comment]
@LouisBrunner sorry for the delay. yeah was elsewhere in my code! Thanks!
