### ISSUE TITLE
Error: Cannot read property 'unshift' of null

### ISSUE THREAD

**Issue by danmckeon** [LouisBrunner/dnd-multi-backend#20]
I'm using `react-dnd-multi-backend` in an Electron app and just received this error from a user on a Windows Surface tablet:

```
error: (appStore) TypeError: Cannot read property 'unshift' of null at TouchBackend.handleMoveStart (C:\Users\XXXXXX\AppData\Local\Programs\XXXXXX\resources\app.asar\node_modules\…
 error: (appStore) TypeError: Cannot read property 'unshift' of null at TouchBackend.handleMoveStart (C:\Users\XXXXXXX\AppData\Local\Programs\XXXXXXX\resources\app.asar\node_modules\react-dnd-touch-backend\dist\Touch.js:384:36) at HTMLDivElement.wrapped
```

Error is raised at this line of `react-dnd-touch-backend`:

```js
key: 'handleMoveStart',
        value: function handleMoveStart(sourceId) {
            this.moveStartSourceIds.unshift(sourceId); //HERE
        }
```

Here is my implementation of `react-dnd-multi-backend`:

```js
render(
  <DragDropContextProvider backend={MultiBackend(HTML5toTouch)}>
    <MuiThemeProviderNext theme={mui1Theme}>
      <MuiThemeProvider muiTheme={muiOldTheme}>
        <Main />
      </MuiThemeProvider>
    </MuiThemeProviderNext>
  </DragDropContextProvider>,
  document.getElementById('root')
);
```

I'm wondering if `react-dnd-multi-backend` may be in `html5backend` mode and then switch to touch and `this.moveStartSourceIds` is `undefined` or something along those lines.

Any help is greatly appreciated! Thank you!

**Comment by engPabloMartinez** [comment]
I'm having the same issue

**Comment by LouisBrunner** [comment]
Hi,

Thanks for the report (with plenty of context)!
I had this issue in the past when the switch wasn't done properly, can you check that you use the last version? (pretty sure you do, but just to be 100% sure)
Anyway, I'll look into it, if you could provide a standalone example that displays the same problem, that would be great (even if it's a small Electron app).

@engPabloMartinez is the issue also happening in an Electon app?

**Comment by engPabloMartinez** [comment]
Hi Louis, I was testing in a pure React environment and I came across this error. I used the last version, thanks

**Comment by danmckeon** [comment]
Hi @LouisBrunner I haven't actually been able to replicate the issue myself, but my alpha user has mostly not run into any issues. It was just during a single session where the issue at the top of this thread arose, which in turn created a number of other issues specific to our app. We also used the latest version of `react-dnd-multi-backend`.
