### ISSUE TITLE
SemVer on React-Dnd-Preview introduces breaking changes

### ISSUE THREAD

**Issue by stusklinar** [LouisBrunner/dnd-multi-backend#24]
Using the SemVer on the dependencies introduces a newer version of React-dnd-preview which uses a significantly higher version of react-dnd which doesn't have support react-15 as it uses the new React 16+ Context APIs.

Thus breaking anything not upgraded.

**Comment by LouisBrunner** [comment]
Hi @stusklinar,

A few of the last versions (react-dnd-multi-backend and react-dnd-review from 3.1.5 to 3.1.7 and dnd-multi-backend 3.1.5 to 3.1.6) were experimental versions used to debug issues other users had. You are right, they should have used prerelease tag, my bad!

However the latest 3.1.8 (3.1.7 for dnd-multi-backend) allows any version of react or react-dnd.

Can you tell me which version you are using right now?

**Comment by LouisBrunner** [comment]
This issue has been closed because there has been no response to our request for more information. With only the information that is currently in the issue, we don't have enough information to take action. Please reach out if you have or find the answers we need so that we can investigate further.
