### ISSUE TITLE
Will this work with older versions of React?

### ISSUE THREAD

**Issue by matjkel** [LouisBrunner/dnd-multi-backend#26]
*Trying on a project using React `v0.14.7`.*

Does `react-dnd-multi-backend` require most recent versions of React?

**Comment by LouisBrunner** [comment]
Hi @matjkel,
The short answer is that I am not sure. I don't think I use any features from the newer versions of React so it should be fine but I can't guarantee it.
Did you try using it and did it break?

**Comment by matjkel** [comment]
Hi @LouisBrunner! It's been tricky to debug as I am by no means a React expert, but I've been running into the following error: 
`Uncaught TypeError: Super expression must either be null or a function, not undefined`

Which is weird, because I don't have any build (`gulp`) errors... 

So, it could be some import or require keeps coming up `undefined` , but I'm sort of stuck atm :/

Looking at the stacktrace the issue _seems_ to be when building the Preview component 🤨

``at _inherits (bundle.js:70767)
    at bundle.js:70774
    at Object.<anonymous> (bundle.js:70799)
    at __webpack_require__ (bundle.js:20)
    at Object.<anonymous> (bundle.js:69992)
    at __webpack_require__ (bundle.js:20)
    at Object.defineProperty.value (bundle.js:69656)
    at __webpack_require__ (bundle.js:20)
    at Object.defineProperty.value (bundle.js:36481)
    at __webpack_require__ (bundle.js:20)``

 ``function _inherits(subClass, superClass) { if (typeof superClass !== "function" && superClass !== null) { throw new TypeError("Super expression must either be null or a function, not " + typeof superClass); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writable: true, configurable: true } }); if (superClass) Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass; }``


``var Preview = (_dec = (0, _reactDnd.DragLayer)(function (monitor) {
  return {
    currentOffset: monitor.getSourceClientOffset(), isDragging: monitor.isDragging(), itemType: monitor.getItemType(), item: monitor.getItem()
  };
}), _dec(_class = (_temp = _class2 = function (_PureComponent) {
  _inherits(Preview, _PureComponent);``

 ``(_react.PureComponent), _class2.defaultProps = { currentOffset: { x: 0, y: 0 }, isDragging: false, itemType: '', item: {} }, _class2.propTypes = {
  currentOffset: _propTypes2.default.shape({ x: _propTypes2.default.number, y: _propTypes2.default.number }),
  isDragging: _propTypes2.default.bool, itemType: _propTypes2.default.string, item: _propTypes2.default.any, generator: _propTypes2.default.func.isRequired
}, _temp)) || _class);
exports.default = Preview;``

 ``var _reactDndPreview = __webpack_require__(949);``

 ``var _Preview = __webpack_require__(945);``

 ``import var __WEBPACK_IMPORTED_MODULE_4_react_dnd_multi_backend__ = __webpack_require__(941);``

**Comment by LouisBrunner** [comment]
Do you have a small example you could give me so I can test/reproduce it easily?
Depending on the difficulty we could easily add support for it!

**Comment by LouisBrunner** [comment]
This issue has been closed because there has been no response to our request for more information. With only the information that is currently in the issue, we don't have enough information to take action. Please reach out if you have or find the answers we need so that we can investigate further.
