### ISSUE TITLE
TypeError: Cannot read property 'getMonitor' of undefined in index js 

### ISSUE THREAD

**Issue by farouk-46015** [LouisBrunner/dnd-multi-backend#30]
TypeError: Cannot read property 'getMonitor' of undefined in index js  

  52 | function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
  53 | 
  54 | var _default = function _default(managerOrOptions) {
> 55 |   if (managerOrOptions.getMonitor) {
  56 |     return new _MultiBackend.default(managerOrOptions);
  57 |   }
  58 |

**Comment by LouisBrunner** [comment]
Hi @farouk-46015 !
Thanks for your report! However I need more information to be able to fix this problem.
Could you post a bit more information about how you use the library (or even better a complete project)?

**Comment by LouisBrunner** [comment]
This issue has been closed because there has been no response to our request for more information. With only the information that is currently in the issue, we don't have enough information to take action. Please reach out if you have or find the answers we need so that we can investigate further.
