### ISSUE TITLE
DragDropContext removed from ReactDND

### ISSUE THREAD

**Issue by vkuba** [LouisBrunner/dnd-multi-backend#32]
Since  v9 : https://github.com/react-dnd/react-dnd/releases/tag/v9.0.0 react DND doesn't support DragDropContext. Is there any way to use dnd-multi-backend with the latest version of the react DND?

**Comment by LouisBrunner** [comment]
HI @vkuba, this problem is being addressed in #31. In a nutshell: I have started work on v9 support and it's close to done, but the v9 non-esm builds are broken so it will need to wait until this has been fixed.
