### ISSUE TITLE
React 19 support

### ISSUE THREAD

**Issue by printfn** [LouisBrunner/dnd-multi-backend#340]
It looks like react-dnd-preview isn't compatible with React 19. I was wondering if it might be possible to get a compatible release with updated peer dependencies?

**Comment by LouisBrunner** [comment]
Of course, I will look into this tomorrow.

**Comment by LouisBrunner** [comment]
@printfn v9.0.0-rc0001 was released with React 19 support. There are no breaking changes apart from the React 19 upgrade. Note that this is currently released under the `next` tag and not under `latest` due to being a pre-release.

**Comment by printfn** [comment]
Excellent, thank you!!

**Comment by printfn** [comment]
Are you considering making a stable release of this soon?

**Comment by LouisBrunner** [comment]
@printfn Can you confirm it is working as expected?

**Comment by printfn** [comment]
Yup, seems to be working!

**Comment by LouisBrunner** [comment]
@printfn Great to hear! I just released v9 on `latest`.
