### ISSUE TITLE
Backends incorrectly treated as constructors

### ISSUE THREAD

**Issue by cormacrelf** [LouisBrunner/dnd-multi-backend#38]
See https://github.com/cormacrelf/angular-skyhook/issues/484, especially:

https://github.com/react-dnd/react-dnd/blob/704245d47892f9d465b1b4465203f5c8464eb5a7/packages/core/html5-backend/src/index.ts#L7-L10

A dnd-core `BackendFactory` is just a function that returns any object that implements `Backend`. MultiBackend.js should not call it with `new backend.backend(...)`. I am frankly surprised this hasn't caused errors before that issue was filed, maybe there is something weirder going on.

**Comment by cormacrelf** [comment]
I figured out why 'backend.backend is not a constructor' hasn't reared its head before.

1. Regular functions like `function Named() {}` or `const anon = function() {}` can be called as constructors.
2. If a regular function doesn't return a value, it is a normal prototypical constructor which returns the newly constructed `this` when it is called with `new`.
3. If a regular-function-constructor returns a value, that is the output of calling it with `new`.
4. Arrow functions are definitely not constructors and will throw an error if you attempt to use them as one.

Upshot: the main backends use arrow functions. Maybe they didn't before. But more likely some users have stopped transpiling that down to `function (...) { return new HTML5Backend(...); }`, and started relying on evergreen browsers' arrow function syntax support.

Essentially, dnd-multi-backend has been relying on **3** for years, and now it's broken because being-functions-but-not-arrow-functions was not a stable part of the dnd-core backend interface.

![Screen Shot 2019-10-19 at 19 49 55](https://user-images.githubusercontent.com/378760/67140770-ac8fa280-f2a9-11e9-8a50-d59c659a170e.png)

**Comment by LouisBrunner** [comment]
Good catch, I don't know why I did it this way. Thanks for the PR!
