### ISSUE TITLE
Bug?: Class constructor HTML5Backend cannot be invoked without 'new'

### ISSUE THREAD

**Issue by de83c78d1f** [LouisBrunner/dnd-multi-backend#40]
Hello and thank you for your work. I use your lib on `5.0.0-rc03`. `React-dnd 9.4.0`
My `App.tsx` file uses custom `HTML5toTouch`:
```typescript
const HTML5toTouch = {
    backends: [
        {
            backend: HTML5Backend,
            transition: MouseTransition
        },
        {
            backend: TouchBackend,
            options: {enableMouseEvents: true},
            preview: true,
            transition: TouchTransition
        }
    ]
};

export class App extends Component {
  public render() {
    return (
      <DndProvider backend={MultiBackend} options={HTML5toTouch}>
        {.....}
      </DndProvider>
    );
  }
}
```
Where HTML5 backend is our fork of official one, and Touch backend is official. I get error attached on screen
![Screenshot from 2019-11-26 15-13-05](https://user-images.githubusercontent.com/39216062/69632565-2d3b7e80-1060-11ea-8747-648ba77c393e.png)

When i go to `node_modules` and add `new` where the error suggests - my app works fine. So the question is: am I using your lib the wrong way or there needs to be `new` keyword?

**Comment by LouisBrunner** [comment]
Hi @de83c78d1f,

As reported in #38, backends were never meant to be treated as constructors, thus the usage of `new` was a mistake on my side.

To allow your custom backend to work again, you can just wrap it in a function (see https://github.com/LouisBrunner/dnd-multi-backend/blob/next/packages/dnd-multi-backend/examples/Backends.js#L110).

Hope that helps!

**Comment by de83c78d1f** [comment]
Thank you for clarification, now it works just fine.
