### ISSUE TITLE
Update peerDependencies to react-dnd 10

### ISSUE THREAD

**Issue by fxOne** [LouisBrunner/dnd-multi-backend#42]
Can you please update the peerDependencies to the latest react-dnd verison as version 10 is available?

https://github.com/LouisBrunner/dnd-multi-backend/blob/37465b5d2e19e155aabcbc65a5bdfadd2dac7f79/packages/react-dnd-multi-backend/package.json#L27
https://github.com/LouisBrunner/dnd-multi-backend/blob/37465b5d2e19e155aabcbc65a5bdfadd2dac7f79/packages/react-dnd-multi-backend/package.json#L28
https://github.com/LouisBrunner/dnd-multi-backend/blob/37465b5d2e19e155aabcbc65a5bdfadd2dac7f79/packages/react-dnd-preview/package.json#L24

**Comment by markfeimer** [comment]
I believe the older libraries are causing some issues on iOS 13 so I am watching this with interest!

**Comment by LouisBrunner** [comment]
I just pushed `5.0.1` which updates all of that. Can you confirm it's working as expected?

Very sorry for the delay!

**Comment by markfeimer** [comment]
I expect to give this a try tomorrow and will report back!  Thank you!

**Comment by markfeimer** [comment]
@LouisBrunner this was exactly what I needed, thank you!

**Comment by LouisBrunner** [comment]
Happy to hear! Thanks for the feedback!
