### ISSUE TITLE
Attempted import error: 'PreviewManager' is not exported from 'dnd-multi-backend'.

### ISSUE THREAD

**Issue by nan140114** [LouisBrunner/dnd-multi-backend#45]
Hello there.

I'm trying to build a react application with these dependencies:

"react-dnd-html5-backend": "10.0.2"
"react-dnd-multi-backend": "5.0.0"
"react-dnd-touch-backend": "10.0.2"

The build scripts throw this error:

```bash
Creating an optimized production build...
Failed to compile.

./node_modules/react-dnd-multi-backend/dist/esm/Preview.js
Attempted import error: 'PreviewManager' is not exported from 'dnd-multi-backend'.
```

I took a look at the dependency tree and react-dnd-multi-backend requires "dnd-multi-backend": "^5.0.0". Maybe the last version v5.0.2 introduces this issue? Thank you so much.

**Comment by nan140114** [comment]
Oh. I got it, the new version of "dnd-multi-backend" removes the PreviewManager module. I'm using 5.0.0 of react-dnd-multi-backend, which requires the 5.0.2 version of dnd-multi-backend. I'm going to update the react-dnd-multi-backend to 5.0.2. Anyway, maybe use exact version numbers could solve the issue?

**Comment by LouisBrunner** [comment]
Hi @nan140114,

Ugh, I didn't think of that at all! I will unpublish the 5.0.2 and republish it as 5.1.0 (as it should have been from the beginning).

Sorry about that!

**Comment by LouisBrunner** [comment]
Actually, it should have been `6.0.0` as there are breaking changes... Anyway, after a few publishes and `npm deprecate`, installing `react-dnd-multi-backend@5.0.0` will yield you `dnd-multi-backend@5.0.1` which are compatible.

Sorry for the confusion! Note that from `react-dnd-multi-backend` perspective, the only changes between `5.0.1` and `6.0.0` is a new `DndProvider` component and a `usePreview` hook, no breaking changes.

**Comment by nan140114** [comment]
Don't apologize!. Thank you for this tool! Sure, I agree. The `6.0.0` looks better Jajaja. Anyway, our workaround was to use the `5.0.2` version. Give me a few hours to check the build with `5.0.0` version. :walking:

**Comment by nan140114** [comment]
It works! Thank you for your time!
