### ISSUE TITLE
Customizable preview portal parent

### ISSUE THREAD

**Issue by dobesv** [LouisBrunner/dnd-multi-backend#47]
Currently the preview portals all use the same parent, which is a div added by the DndProvider.

However, if you are dragging something that is itself in a portal that is in a div that comes after that common parent, then the drag preview might be behind that other element.

It would be nice if instead of `DndProvider` creating its own `div` we could specify the `div` to use (e.g. `document.getElementById('react-root')`

The current workaround is to just make our own version of `Preview` and `DndProvider` that use the portal parent that we want to use.

**Comment by LouisBrunner** [comment]
Hi @dobesv,

Thank you for your report, I introduced the `DndProvider` wrapper in the latest release and it is good to it get some use!

Adding a way to inject your own `div` seems reasonable so I will look into it soon, however would you mind showing me an example of the case you are describing here:
> However, if you are dragging something that is itself in a portal that is in a div that comes after that common parent, then the drag preview might be behind that other element.
As I am not sure I entirely understand.

**Comment by dobesv** [comment]
To reproduce:

1. Create a modal element in a portal, parent element is document.body
2. Try and drag things around in there

Although maybe we are using the provider differently than you intended.  We have one global DND provider inside react root.  I'm not sure if we're supposed to have multiple of these providers, used separately in components that support DND.

**Comment by LouisBrunner** [comment]
@dobesv,

Sorry for the delay. You are using it correctly, I don't think it's useful to have more than one provider.

I still have difficulty picturing what issues you are running in (a repo which reproduces the issue would greatly appreciated!).

But from what I understand, you would be fine with passing a `ref` to `DndProvider` which would point to the div you want to use for your portal?

**Comment by dobesv** [comment]
@LouisBrunner 

Sorry if I wasn't clear in my description, it's a bit tricky to explain, I guess.

Let's say your app boots up and you have the drag and drop stuff initialized, your DOM might look something like:

```
<body>
<div id="react-root">
<div> ... app stuff ... </div>
<div> ... portal created for DnD portal parent ... </div>
</div>
</body>
```

Now if you create a modal in a new div:

```
<body>
<div id="react-root">
<div> ... app stuff ... </div>
<div> ... portal created for DnD portal parent ... </div>
<div> ... portal created for modal ... </div>
</div>
</body>
```

If the modal has draggable elements, they are inserted into the `<div> ... portal created for DnD purposes ... </div>`, which is behind the `<div> ... portal created for modal ... </div>`, so those dragged elements are not visible when dragged.

Our way of solving this is to specify the div to insert the drag preview into when dragging to be the `<div id="react-root">` element.  That way all the portals are added to the same parent, so the newest portal added is always on top of all the other portals and the main application, including drag and drop previews.

Looking at the code now it seems like maybe we could have just replaced `DndProvider` with our own component that does this, but we actually replaced `DndProvider` and `Preview` for some reason, I can't remember why it turned out that way.

**Comment by dobesv** [comment]
To answer your second question, yes if I could just pass in the element (or a ref to it is fine also) that would be used as the portal parent for the previews, that would probably solve the problem.
