### ISSUE TITLE
Position error with bootstrap.

### ISSUE THREAD

**Issue by andersonrocha0** [LouisBrunner/dnd-multi-backend#5]
Error with small screen sizes and bootstrap.

I made a gif to help.

[GIF](http://imgur.com/a/TV9K8)

**Comment by andersonrocha0** [comment]
I'm using the touch to tests. With the mouse the problem no occurs.

**Comment by LouisBrunner** [comment]
Hello,

Thanks for the feedback! I am aware that some shift can happen when using the Preview in Touch mode, but I have never seen anything that violent.

I will look into fixing it, but could you try to create a small example that demonstrate your problem?

**Comment by LouisBrunner** [comment]
@andersonrocha0,

I don't know if you are still using `dnd-multi-backend` but I would be interested to hear from you around this issue.

I have created a new examples page (https://github.com/LouisBrunner/dnd-multi-backend/blob/master/packages/react-dnd-preview/examples/offset/App.js) dedicated to testing preview offsets, and I would love to add similar styling as you had in your example so we can reproduce (and fix!) the issue.

**Comment by LouisBrunner** [comment]
For future reference, I have also seen this issue when the `<Preview />` component is rendered too deep inside the DOM (esp. inside other `position: absolute` tags).

As we have different ways to address this issue now, I will close this for now, feel free to reopen if you encounter this issue again.
