### ISSUE TITLE
Unable to import usePreview with TypeScript React

### ISSUE THREAD

**Issue by CayenneLow** [LouisBrunner/dnd-multi-backend#51]
I'm trying to import the usePreview hook via:
``` javascript
import { usePreview } from 'react-dnd-multi-backend';
```
but it's giving me the following error:
```
Module '"../../../node_modules/@types/react-dnd-multi-backend"' has no exported member 'usePreview'.
```
Below are my installed dependencies:
```
"@types/react-dnd-multi-backend": "^6.0.0",
"react-dnd": "^11.1.1",
"react-dnd-html5-backend": "^11.1.1",
"react-dnd-multi-backend": "^6.0.2",
"react-dnd-touch-backend": "^11.1.3",
```

Would be great if I could get some help on this.

Thanks in advance!

**Comment by LouisBrunner** [comment]
Hi,

At the moment, the TypeScript type definitions are managed by [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped#readme) (great project!).

You will need to log an issue with them directly. I will see if I have time to contribute a patch to their repo.

**Comment by LouisBrunner** [comment]
Just wanted to update that 7.0.0 will release with full TypeScript support
