### ISSUE TITLE
PreventDefault errors

### ISSUE THREAD

**Issue by R4VANG3R** [LouisBrunner/dnd-multi-backend#58]
I'm getting an error on `MultiBackend.js:135`:

> [Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080

when used in combination with[ `rc-slider`](https://github.com/react-component/slider).

I've made a minimal example here: https://codesandbox.io/s/dnd-slider-0npvo?file=/src/App.js

To reproduce:
- Open the example on a mobile device
- Tap on the slider
- See error in console

**Comment by LouisBrunner** [comment]
Thanks for your report @R4VANG3R!

That's interesting, I suppose the event duplication is less than ideal... I will look into why it's being considered passive for some reason.
