### ISSUE TITLE
`useObservePreviews` is not exported from `react-dnd-multi-backend`

### ISSUE THREAD

**Issue by JacksonGariety** [LouisBrunner/dnd-multi-backend#65]
Shouldn't `useObservePreviews` be exported? Otherwise, how can we determine whether to draw the separate preview layer downstream in the component hierarchy?

**Comment by LouisBrunner** [comment]
Hi @JacksonGariety,

You should use [`usePreview`](https://github.com/LouisBrunner/dnd-multi-backend/tree/main/packages/react-dnd-multi-backend#preview), or does that not fit your use case?

**Comment by JacksonGariety** [comment]
@LouisBrunner I was using the `<Preview generator={generatePreview} />` format and noticed that the `display` property was not present. I realized that I could get it from `useObservePreviews`, but I guess I could've used `usePreview` all along. Thanks.

**Comment by LouisBrunner** [comment]
Note that you can continue using `<Preview generator={generatePreview} />` if you prefer that format, it will only call and display your `generatePreview` if needed (based on `useObservePreviews` internally).
