### ISSUE TITLE
Touch preview is not working on the first try

### ISSUE THREAD

**Issue by yunusemredilber** [LouisBrunner/dnd-multi-backend#66]
Touch preview is not working on the first try. But it working perfectly after. At first, I noticed the problem with my app. Later I noticed that the problem is also on your sample page. This problem happens on both my computer and my phone.

Screen recordings:

https://user-images.githubusercontent.com/46731483/109398477-40698800-794e-11eb-837b-8afa9c1f59c7.mov

https://user-images.githubusercontent.com/46731483/109398520-81fa3300-794e-11eb-874f-1c1f98294b79.MP4

**Comment by LouisBrunner** [comment]
Hi @yunusemredilber,

Thanks for your report! Just to be clear, you are using `7.0.0-alpha.1` right?

**Comment by yunusemredilber** [comment]
Yes. My current dependencies: 
```
"react-dnd": "^11.1.3",
"rdndmb-html5-to-touch": "^7.0.0-alpha.1",
"react-dnd-multi-backend": "^7.0.0-alpha.1",
```

**Comment by LouisBrunner** [comment]
Thanks for the confirmation.

This is the reason I haven't released it as part of `latest`, I haven't been able to figure out that issue!
It's the next thing on my backlog but I would love some help.

**Comment by yunusemredilber** [comment]
Translate values are NaN at first drag. I think it breaking over here
https://github.com/LouisBrunner/dnd-multi-backend/blob/f25d895001d256ff947ca497c84ee2d3c9c891fd/packages/react-dnd-preview/src/offsets.ts#L33

As far as I can see, Getting a null-related NaN value looks not possible really.  Nevertheless, I wanted to share in case anyone wants to investigate my findings by examining them.

<img width="834" alt="Screen Shot 2021-02-28 at 22 25 46" src="https://user-images.githubusercontent.com/46731483/109430743-ea5f1800-7a13-11eb-94d5-2d5f4055deb9.png">

**Comment by LouisBrunner** [comment]
Ah right yes, that's as far as I got it too. I couldn't find a reason why a few of the `monitor` functions return `null`.

**Comment by btahir** [comment]
I'm having this issue as well. Has there been any progress on solving it? :)

**Comment by LouisBrunner** [comment]
I merged a fix for this issue (it's still slightly offset during that first touch event but it's at least usable).

I will try to get it published as `7.0.0-alpha.2` today.

**Comment by RouvenGonzalez** [comment]
Is there an update on this issue? 
Im running into the same problem using version alpha.4

**Comment by AmlisPanda** [comment]
Same problem too with version alpha.4 :(
