### ISSUE TITLE
error: You must specify a valid 'transition' property

### ISSUE THREAD

**Issue by marcohamersma** [LouisBrunner/dnd-multi-backend#68]
Heya,
I'm using `react-dnd-multi-backend` with `rdndmb-html5-to-touch` as described [in the readme](https://github.com/LouisBrunner/dnd-multi-backend/tree/main/packages/rdndmb-html5-to-touch), but I'm getting an error when loading the page.  

```
You must specify a valid 'transition' property (either undefined or the return of 'createTransition') in your Backend entry: [object Object]
```

I've created [a codesandbox](https://codesandbox.io/s/multi-backend-error-e4yq6) to demonstrate.

I also tried using the "old API" approach described in the readme, but that leads to another error. What is the correct way to implement this library at the moment?

**Comment by LouisBrunner** [comment]
Hi,

I don't know if CodeSandox shows `npm install` warning but it would probably tell you that  `react-dnd-multi-backend` needs to be at version `7.0.0-alpha.2` while it is currently pinned at `6.0.2` in your example. Updating the dependency fix it: https://codesandbox.io/s/multi-backend-error-forked-68gw1

Can you confirm is that fixes your problem?

**Comment by marcohamersma** [comment]
Hello Louis, 
Thanks for the fast reply. Changing the dependency version seems to work. I didn't spot this locally (there's a lot of warnings at our end because of nested modules like webpacker). Anyway, thanks for the help!
