### ISSUE TITLE
Change peerDeps to support react 16

### ISSUE THREAD

**Issue by texels** [LouisBrunner/dnd-multi-backend#70]
If there isn't a reason to require 17, can you please allow 16 as well? (alpha-1 used 16)
```
"peerDependencies": {
    "react": "^16.14.0 || ^17.0.2",
    "react-dom": "^16.14.0 || ^17.0.2"
  },
```

**Comment by LouisBrunner** [comment]
Hi @texels,

I remember having issues with 16 but that should be easy enough to do.

**Comment by LouisBrunner** [comment]
I just pushed `7.0.0-alpha.3` which address this
