### ISSUE TITLE
Determine which backend is currently in use

### ISSUE THREAD

**Issue by dotmlj** [LouisBrunner/dnd-multi-backend#74]
react-dnd-multi-backend@7.0.0-alpha.4

Is there a way to determine which backend is currently in use, so the layout and functionality of the Preview can be altered based on this?

Thanks

**Comment by LouisBrunner** [comment]
Hi @dotmlj,

Would passing this information as part of `usePreview`'s result or `Preview`'s props be enough?

**Comment by dobesv** [comment]
We actually have a different use case for knowing the backend, which is we want to have some places where touch is not supported for drag and drop, but others where it is supported.

**Comment by LouisBrunner** [comment]
Using `useMultiDrag` (and it's drop equivalent), you can explicitly decide which part can be use to drag with Touch, HTML5, etc 

https://github.com/LouisBrunner/dnd-multi-backend/tree/main/packages/react-dnd-multi-backend#usemultidrag

**Comment by dobesv** [comment]
Nice, thanks!

**Comment by LouisBrunner** [comment]
@dotmlj As there is a mechanism to do this behaviour, I will be closing this issue. Feel free to reopen if `useMultiDrag` doesn't work for you.
