### ISSUE TITLE
Preview position is different on first drag (touch)

### ISSUE THREAD

**Issue by Raflos10** [LouisBrunner/dnd-multi-backend#75]
Reproduce:
Test the [example](https://louisbrunner.github.io/dnd-multi-backend/examples/react-dnd-multi-backend.html ) and try using mobile touch mode on any of the boxes. The very first time, the preview's top-left corner will be exactly on the mouse. Then every subsequent try, it will be in the proper location. 
It seems kind of inconsequential in the example page, but it's really noticeable in a project I'm working on.

**Comment by LouisBrunner** [comment]
@Raflos10 This is a known bug unfortunately. IIRC the first call to `useDragLayer` doesn't return the right values to render the preview correctly. If you want to investigate the issue yourself, that would be the first place I check.

**Comment by LouisBrunner** [comment]
This issue has now been resolved thanks to @yongla and their great report in #100. Fix is now live with `7.1.3`
