### ISSUE TITLE
Mouse drag drop not working

### ISSUE THREAD

**Issue by Shivam1307** [LouisBrunner/dnd-multi-backend#79]
I have used react-dnd-multi-backend with two backed one is HTML5Backend and KeyboardBackend.
When I drag item using keyboard shortcut (ctrl+d) and drop on any target (enter key) it drops the item . After that I tried it to drag using mouse then it is not working.

Please someone help me to resolve above issue.

**Comment by LouisBrunner** [comment]
Hi @Shivam1307,

Could you provide a minimal reproducible example? (if possible a snippet or repository that demonstrate the issue without too much extra fluff)

**Comment by LouisBrunner** [comment]
Closing as stale, feel free to reopen with more details.
