### ISSUE TITLE
Is there a reason for why 7.0.0 is still in alpha phase?

### ISSUE THREAD

**Issue by Jonathansw** [LouisBrunner/dnd-multi-backend#88]
It looks like 7.0.0 has been in dev for 2 yearsish.  Was wondering if there was a timeline for moving out of alpha?  Or what the current issues are with the build.

**Comment by LouisBrunner** [comment]
I can push 7.0.0 as most people seem to be happy with it but I will probably jump directly to 8.0.0 to upgrade to the newer React-DnD

**Comment by LouisBrunner** [comment]
@Jonathansw `7.0.0` is officially out, sorry for the delay 😉
