### ISSUE TITLE
Example application broken

### ISSUE THREAD

**Issue by deltakapp** [LouisBrunner/dnd-multi-backend#94]
The example application at https://louisbrunner.github.io/dnd-multi-backend/examples/react-dnd-multi-backend.html
is broken on firefox v105 and chrome v105.

Error message:
React is not working

![image](https://user-images.githubusercontent.com/69483547/192106609-3132242d-f993-41de-8e49-72f4e849b8ad.png)

**Comment by LouisBrunner** [comment]
Yeah, as document in #78, I couldn't get the pure ESM build working. I did forget that this is used by NPM though, so I will revert `main` and keep the changes on another branch for now.
