### ISSUE TITLE
Incorrect peer dependency.

### ISSUE THREAD

**Issue by Hardel-DW** [LouisBrunner/dnd-multi-backend#96]
Simply updating the peers dependency to version 16 is not necessary.
Currently in version 16.0.1.

warning " > react-dnd-preview@7.1.1" has incorrect peer dependency "react-dnd@13.1.1 - 15.1.2".

**Comment by LouisBrunner** [comment]
@Hardel-DW v7 doesn't support react-dnd v16, see #78 for details
